version: '3'
services:
  rabbitmq:
    build: .
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: noah
      RABBITMQ_DEFAULT_PASS: herron
    ports:
    - 15672:15672
    - 5672:5672
    - 1883:1883
