version: '3'
services:
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbit
    ports:
    - 15672:15672
    - 5672:5672
    - 1883:1883
  db:
    image: thomastodon/mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: haus
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
    - 3306:3306