resources:
- name: code
  type: git
  source:
    uri: git@github.com:thomastodon/haus.git
    branch: wip/pipeline
    private_key: {{code_private_key}}

jobs:
- name: test
  plan:
  - get: code
    trigger: true
  - task: unit-test
    file: code/pipeline/unit-test.yml