resources:
- name: code
  type: git
  source:
    uri: git@github.com:thomastodon/haus.git
    branch: wip/pipeline
    private_key: {{code_private_key}}

jobs:
- name: test
  plan:
  - get: code
    trigger: true
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: 8
      inputs:
      - name: code
      run:
        dir: code
        path: ./gradlew
        args:
        - backend:unitTest