spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: noah
    password: herron
  cloud:
    stream:
      bindings:
        temperature:
          destination: temperature
          group: haus
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: dialects.MySQL5MyISAMDialect
  datasource:
    url: jdbc:mysql://localhost:3306/haus
    username: noah
    password: herron