spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: noah
    password: herron
  cloud:
    stream:
      bindings:
        temperature:
          destination: temperature
          group: haus