rabbitmq:
  host: localhost
  port: 5672
  username: noah
  password: herron
  exchangeName: temperature
  queueName: temperature-queue
  routingKey: temperature.created

spring:
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: dialects.MySQL5MyISAMDialect
  datasource:
    url: jdbc:mysql://localhost:3306/haus
    username: noah
    password: herron